### ISSUE TITLE
Android error if request more than once for permissions

### ISSUE THREAD

**Issue by Daxito** [NathanaelA/nativescript-permissions#16]
I have this app that tracks user location, so I deny permission the first time it asked me on screen X, then I went to some other screen Y and came back to screen X and it asked for permissions again but after selecting "Deny" this second time it throw an error on this line:

`if (typeof promises.granted !== 'function') {
            return;
        }`

Basically the error says that "promises" is undefined, so it cannot read "granted", does not matter if granted was there or not, promises is undefined...

Using NS 2.3.0 and plugin version 1.2.0

Thanks!

**Comment by NathanaelA** [comment]
Fixed in v1.2.1
