### ISSUE TITLE
tns-platform-declarations doesn't have android.Manifest

### ISSUE THREAD

**Issue by pocesar** [NathanaelA/nativescript-permissions#22]
I'm coding on API LEVEL 23, and when adding the android17.d.ts to the references.d.ts file, there's no member Manifest in the `android` namespace. Is it a problem with the `tns-platform-declarations` or with this module?

**Comment by NathanaelA** [comment]
Actually typing are optional.  For those of us who prefer to use JS, typing's are pointless.  

Most typing's in my plugin are done by other users who use TS...  We could add it to the existing permissions typing's file if you want to do a pull request, I'm not opposed to adding it...

**Comment by pocesar** [comment]
I'll see if the NS devs will either update their typings, or accept a PR. if they won't, then I'll send you a PR. 

I use TS everywhere heh

**Comment by NathanaelA** [comment]
Typings have now been included for the last couple versions.
