### ISSUE TITLE
Can't request permission ACTIVITY_RECOGNITION

### ISSUE THREAD

**Issue by surdu** [NathanaelA/nativescript-permissions#26]
I'm trying to request permission for `com.google.android.gms.permission.ACTIVITY_RECOGNITION` but when I write this

	permissions.requestPermission(com.google.android.gms.permission.ACTIVITY_RECOGNITION, "bla")
	.then(function() {
		// ...
	});

I get the error: `Cannot read property ACTIVITY_RECOGNITION of undefined`

**Comment by NathanaelA** [comment]
I do not believe this permission is one you need to do at runtime.  You only need to add it to the Manifest for compile time permission.
