### ISSUE TITLE
support  nativescript 4.0+

### ISSUE THREAD

**Issue by zuohuadong** [NathanaelA/nativescript-permissions#31]
It does not work properly.  thanks～

**Comment by NathanaelA** [comment]
To my knowledge nothing in NS 4 should have broke this plugin; what happens when you try the demo app in Android 6+?

**Comment by NathanaelA** [comment]
I have tested the current version in NS4 and it works fine.   I also updated the demo, as the demo used the old NS1/NS2 `console.dump` rather than `console.dir`; but beyond that -- the demo also worked fine...
