### ISSUE TITLE
Unable to request 'android.permission.BIND_DEVICE_ADMIN'

### ISSUE THREAD

**Issue by DeadEnglish** [NathanaelA/nativescript-permissions#36]
I have `android.permission.BIND_DEVICE_ADMIN` within my AndroidManifest.xml as per my other permissions but currently I'm unable to request permission for it. There's no "toast" notification to accept/deny as with the other permissions. 

The request permissions code is as follows
```typescript
requestPermission(android.Manifest.permission.BIND_DEVICE_ADMIN, 'needed for kiosk mode').then(function () {
				console.log("permission for BIND_DEVICE_ADMIN");
			})
			.catch(function () {
				console.log("no perms for BIND_DEVICE_ADMIN");
			});
```

**Comment by NathanaelA** [comment]
Do you get anything at all?   
Does the promise resolve or reject?
What happens if you add:  
   console.log("Bind:", android.Manifest.permission.BIND_DEVICE_ADMIN);
Does it actually print a value out?

**Comment by DeadEnglish** [comment]
The promise is rejected and caught within the `.catch`. Console logging `console.log("Bind:", android.Manifest.permission.BIND_DEVICE_ADMIN);` returns the following:

```
Bind: android.permission.BIND_DEVICE_ADMIN
```

console logging the return within the `.catch` adding `promise` within the `.catch` function parameters returns the following also:

``` javascript
promise {
    "android.permission.BIND_DEVICE_ADMIN": false
}
````

**Comment by NathanaelA** [comment]
Do you have this permission and a receiver in your manifest file?

https://developer.android.com/guide/topics/admin/device-admin

**Comment by DeadEnglish** [comment]
I did have both but it seems like 'BIND_DEVICE_ADMIN' isn't accessible at all through the application, it seems to be required when setting the device admin. Closing as this isn't an issue with the plugin, just unclear instructions when using kiosk mode in nativescript.
