### ISSUE TITLE
hasPermission function returns always false

### ISSUE THREAD

**Issue by standevo** [NathanaelA/nativescript-permissions#42]
permissions.hasPermission(android.Manifest.permission.WRITE_SETTINGS) returns always false even if the permission was granted before

**Comment by NathanaelA** [comment]
What OS is this on?

**Comment by standevo** [comment]
@NathanaelA, Hi, I have this problem on Android (simulator & device)

**Comment by NathanaelA** [comment]
Can you try the demo and see what happens?

**Comment by standevo** [comment]
Demo doesn't use any hasPermission method only request

**Comment by NathanaelA** [comment]
I just realized you asked about the `WRITE_SETTINGS` -- that is a WEIRD special permission.   Checking the code hasPermission does not have the code in it to check for it...

**Comment by NathanaelA** [comment]
This has been fixed in v1.3.9 and the demo has been updated to show and use `hasPermission`
