### ISSUE TITLE
App to app permissions

### ISSUE THREAD

**Issue by Zmast1private-Ltd** [NathanaelA/nativescript-permissions#46]
Hi Nathaneal,

We used most of your plugins more than 25 in our app , all are useful ,but beyond that we need some plugins for app to app permissions to fetch data from their apps like (Fitbit,Garmin) to our app ,but we achieved for one device named as googlefit(Apple Healthkit) and got a output successfully, in the same way we are looking for fitbit,garmin and some devices,,can you have any idea on how to do this??

Note:
how can a plugin can be written by own ?? for our business logic needs can we write a own plugin??is it achievable

**Comment by NathanaelA** [comment]
Hi, this is better handled via email; you can contact me at nanderson@nstudio.io -- however, my blog https://fluentreports.com/blog has an articles on writing plugins.
