### ISSUE TITLE
Cant request for READ_PRIVILEGED_PHONE_STATE permission 

### ISSUE THREAD

**Issue by NavruzbekNoraliev** [NathanaelA/nativescript-permissions#47]
HI i encountered problem while testing in my physical device with os version android 10

Error: java.lang.IllegalArgumentException: permission is null
 
I'm asking for permission  READ_PRIVILEGED_PHONE_STATE  to get imei of device

**Comment by NathanaelA** [comment]
This is to be expected; see:
- https://developer.android.com/about/versions/10/privacy/changes#non-resettable-device-ids
- https://source.android.com/devices/tech/config/device-identifiers

Unless your app is a carrier app, you can't get that permission.

**Comment by vaimeo** [comment]
How we can setup our app as carrier app?

**Comment by NathanaelA** [comment]
This means it is signed by the  carrier (i.e. like AT&T, Verizon, etc) and the app is sold typically as part of the phone.
