### ISSUE TITLE
Compile Time Error for 1.3.12

### ISSUE THREAD

**Issue by SingleMalted** [NathanaelA/nativescript-permissions#48]
Hey Nathanael,

Our CI patched this plugin and failed during build. Rolling back to `1.3.11` fixed the issue.

**Error code:**
```
ERROR in ../node_modules/@master.technology/permissions/permissions.js 67:46
Module parse failed: Unexpected token (67:46)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|                     // We will get a Status=0 before we get the first real status...
|                     if (status === 0) { return; }
>                     const owner = this._owner?.get();
|                     if (owner) {
|                         if (LOCATION.has()) {
 @ ../node_modules/nativescript-permissions/permissions.js 13:17-58
```
Thanks

**Comment by NathanaelA** [comment]
Ugh, `?.` is supported by all the NS engines, so why the toolchain is having issues with it, is anyone's guess.     Thanks,  I'll down grade the JS code to use the obsolete older methods.

**Comment by NathanaelA** [comment]
I've pushed a v2.01 that uses the older `const owner = this._owner && this._owner.get()` rather than the more modern `?.` syntax.   Thanks for letting me know...

**Comment by SingleMalted** [comment]
That was the issue, optional chaining syntax? That's weird.😕

Oh well, thanks for fixing... working fine now.
