### ISSUE TITLE
Issue for ios, Android var is not found

### ISSUE THREAD

**Issue by Daxito** [NathanaelA/nativescript-permissions#7]
If I require the plugin at the top of my js file, then it would crash on ios, basically saying that "android" is not found or undefined, line 17

```
// If this isn't a Android platform we will exit and do nothing.
if (!android) {
    return;
}
```

But instead it crashes.

Nice plugin!

Thanks

**Comment by NathanaelA** [comment]
This was actually fixed yesterday  afternoon in v1.1.2   ;-)
